version: "3.6"
services:
  postgres:
    image: postgres:9.6.6-alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123


